### ISSUE TITLE
Getting gce Ansible module in create.yaml when initialize the role with driver gce

### ISSUE THREAD

**Issue by WissemChb** [ansible-community/molecule-gce#20]
Hi,

When we have executed the `molecule init role <role_name> -d gce` we found that the `create.yaml` file contains the deprecated ansible `gce` module rather then `google.cloud.gcp_compute_instance`.  We checked the source code of the driver we found that the right ansible module `google.cloud.gcp_compute_instance` is added (please see [file](https://github.com/ansible-community/molecule-gce/blob/main/src/molecule_gce/playbooks/tasks/create_linux_instance.yml)) . Can anyone have an idea about the error please ?

## molecule info

```shell
molecule 3.4.0 using python 3.9
    ansible:2.11.3
    delegated:3.4.0 from molecule
    docker:0.2.4 from molecule_docker
    ec2:0.3 from molecule_ec2
    gce:0.2 from molecule_gce
```
## Generated create.yaml file content
```yaml
---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  vars:
    ssh_port: 22
    ssh_user: "{{ lookup('env', 'USER') }}"
    ssh_identity_file: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/ssh_key"
  tasks:
    - name: Create keypair
      openssh_keypair:
        comment: "{{ ssh_user }}@example.com"
        path: "{{ ssh_identity_file }}"
      register: keypair

    - name: Create molecule instance(s)
      gce:
        instance_names: "{{ item.name }}"
        zone: "{{ item.zone }}"
        machine_type: "{{ item.machine_type }}"
        image: "{{ item.image }}"
        service_account_email: "{{ lookup('env', 'GCE_SERVICE_ACCOUNT_EMAIL') }}"
        credentials_file: "{{ lookup('env', 'GCE_CREDENTIALS_FILE') }}"
        project_id: "{{ lookup('env', 'GCE_PROJECT_ID') }}"
        metadata: "{\"ssh-keys\": \"{{ ssh_user }}:{{ keypair.public_key }}\"}"
      register: server
      with_items: "{{ molecule_yml.platforms }}"
      async: 7200
      poll: 0

    - name: Wait for instance(s) creation to complete
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: gce_jobs
      until: gce_jobs.finished
      retries: 300
      with_items: "{{ server.results }}"

    # Mandatory configuration for Molecule to function.

    - name: Populate instance config dict
      set_fact:
        instance_conf_dict: {
          'instance': "{{ item.instance_data[0].name }}",
          'address': "{{ item.instance_data[0].public_ip }}",
          'user': "{{ ssh_user }}",
          'port': "{{ ssh_port }}",
          'identity_file': "{{ ssh_identity_file }}", }
      with_items: "{{ gce_jobs.results }}"
      register: instance_config_dict
      when: server.changed | bool

    - name: Convert instance config dict to a list
      set_fact:
        instance_conf: "{{ instance_config_dict.results | map(attribute='ansible_facts.instance_conf_dict') | list }}"
      when: server.changed | bool

    - name: Dump instance config
      copy:
        content: "{{ instance_conf | to_json | from_json | molecule_to_yaml | molecule_header }}"
        dest: "{{ molecule_instance_config }}"
      when: server.changed | bool

    - name: Wait for SSH
      wait_for:
        port: "{{ ssh_port }}"
        host: "{{ item.address }}"
        search_regex: SSH
        delay: 10
      with_items: "{{ lookup('file', molecule_instance_config) | molecule_from_yaml }}"
```

## molecule.yaml generated
```yaml
---
dependency:
  name: galaxy
driver:
  name: gce
platforms:
  - name: instance
provisioner:
  name: ansible
verifier:
  name: ansible
```

## Expected behaviour:

`molecule create -s  <scenario>` create the instance in GCP

## Actual behaviour
Error: 
```json
ERROR! [DEPRECATED]: community.general.gce has been removed. Use google.cloud.gcp_compute_instance instead. This feature was removed from community.general in version 2.0.0. Please update your playbooks.
```
